-- Cards seed data — 80 cards, 8 suits, with rarity field
-- Rarity tiers: common > uncommon > rare > legendary
-- Weights are aligned with rarity: common=high, legendary=0.1

TRUNCATE TABLE cards RESTART IDENTITY CASCADE;

INSERT INTO cards (name_ua, name_en, description_ua, description_en, suit, type, weight, rounds, is_active, created_at, updated_at) VALUES

-- CHAINS (обмеження) — common 1.2–1.3 | uncommon 0.9–1.0 | rare 0.5–0.6
('Гаманець-скнара', 'Tight Budget', 'Ваш бюджет обмежено до $100. Кожне рішення має бути обґрунтовано економічно.', 'Your budget is limited to $100. Every decision must be economically justified.', 'chains', 'constraint', 1.2, '{1,2,3}', true, NOW(), NOW()),
('Команда в карантині', 'Team Quarantine', 'Один учасник команди мовчить наступні 10 хвилин. Оберіть жертву.', 'One team member stays silent for the next 10 minutes. Choose your victim.', 'chains', 'constraint', 1.0, '{1,2,3,4}', true, NOW(), NOW()),
('Без інтернету', 'No Internet', 'Заборонено гуглити щось наступні 15 хвилин. Тільки знання з голови.', 'No googling for the next 15 minutes. Only knowledge from memory.', 'chains', 'constraint', 1.3, '{1,2,3,4,5}', true, NOW(), NOW()),
('Технічний борг', 'Technical Debt', 'Ваше рішення має використовувати застарілу технологію на вибір ведучого.', 'Your solution must use an outdated technology chosen by the host.', 'chains', 'constraint', 0.9, '{2,3,4}', true, NOW(), NOW()),
('Заморожений фічер', 'Feature Freeze', 'Ви не можете додавати нові функції до кінця раунду. Тільки оптимізація.', 'You cannot add new features until the end of the round. Optimization only.', 'chains', 'constraint', 1.0, '{3,4,5}', true, NOW(), NOW()),
('Один слайд', 'One Slide Only', 'Ваша презентація — рівно один слайд. Більше не можна.', 'Your presentation is exactly one slide. No more allowed.', 'chains', 'constraint', 0.6, '{4,5}', true, NOW(), NOW()),
('Мовний бар''єр', 'Language Barrier', 'Всі пояснення наступні 5 хвилин — тільки англійською. Без винятків.', 'All explanations for the next 5 minutes must be in English only.', 'chains', 'constraint', 1.2, '{1,2,3,4,5}', true, NOW(), NOW()),
('Без ML', 'No ML Allowed', 'Ваш AI-продукт не може використовувати машинне навчання. Знайдіть інший підхід.', 'Your AI product cannot use machine learning. Find another approach.', 'chains', 'constraint', 0.9, '{1,2,3}', true, NOW(), NOW()),
('Стартап без назви', 'Nameless Startup', 'Ваш продукт не може мати назву до кінця цього раунду. Описуйте тільки функціями.', 'Your product cannot have a name until the end of this round. Describe by features only.', 'chains', 'constraint', 1.2, '{1,2}', true, NOW(), NOW()),
('Регулятор проти вас', 'Regulatory Nightmare', 'GDPR, HIPAA і ще три закони яких ви не знаєте. Ваш юрист у відпустці.', 'GDPR, HIPAA and three more laws you don''t know. Your lawyer is on vacation.', 'chains', 'constraint', 0.5, '{3,4,5}', true, NOW(), NOW()),

-- VIRUS (мутації) — common 1.2–1.3 | uncommon 0.9–1.0 | rare 0.5
('Зміна ЦА', 'Pivot Audience', 'Ваша цільова аудиторія тепер пенсіонери 65+. Переосмисліть продукт.', 'Your target audience is now retirees 65+. Rethink your product.', 'virus', 'mutation', 1.3, '{2,3,4}', true, NOW(), NOW()),
('Конкурент скопіював', 'Copycat Competitor', 'Великий tech-гігант анонсував точно такий самий продукт. Чим ви відрізняєтесь?', 'A big tech giant just announced exactly the same product. What makes you different?', 'virus', 'mutation', 1.0, '{3,4,5}', true, NOW(), NOW()),
('Нова вимога інвестора', 'Investor Demand', 'Інвестор вимагає додати блокчейн до вашого рішення. Будь-яким чином.', 'The investor demands you add blockchain to your solution. Any way possible.', 'virus', 'mutation', 0.5, '{2,3,4,5}', true, NOW(), NOW()),
('Вірусний тренд', 'Viral Trend', 'Ваш продукт тепер має бути пов''язаний з останнім вірусним мемом. Обов''язково.', 'Your product must now be connected to the latest viral meme. Mandatory.', 'virus', 'mutation', 1.3, '{1,2,3}', true, NOW(), NOW()),
('Зміна платформи', 'Platform Shift', 'Ваш продукт більше не веб. Тільки голосовий інтерфейс або AR.', 'Your product is no longer web. Voice interface or AR only.', 'virus', 'mutation', 1.0, '{3,4}', true, NOW(), NOW()),
('Партнерство по примусу', 'Forced Partnership', 'Ви мусите інтегруватися з продуктом іншої команди. Домовтесь за 5 хвилин.', 'You must integrate with another team''s product. Negotiate within 5 minutes.', 'virus', 'mutation', 0.5, '{3,4,5}', true, NOW(), NOW()),
('Зелений мандат', 'Green Mandate', 'Продукт має бути carbon-neutral і довести це числами. Зараз.', 'The product must be carbon-neutral and prove it with numbers. Right now.', 'virus', 'mutation', 0.9, '{2,3,4,5}', true, NOW(), NOW()),
('Локалізація за годину', 'Emergency Localization', 'Ринок змінився — ваш продукт має підтримувати ще дві мови. Назвіть які.', 'Market changed — your product must support two more languages. Name them.', 'virus', 'mutation', 1.2, '{2,3,4}', true, NOW(), NOW()),
('AI замість вас', 'AI Takeover', 'Половину функцій вашого продукту тепер виконує ChatGPT безкоштовно. Що залишилось?', 'Half of your product features are now free in ChatGPT. What remains?', 'virus', 'mutation', 1.0, '{3,4,5}', true, NOW(), NOW()),
('Дата-ліцензія відкликана', 'Data License Revoked', 'Ваш основний датасет більше недоступний. Знайдіть альтернативу за 3 хвилини.', 'Your main dataset is no longer available. Find an alternative in 3 minutes.', 'virus', 'mutation', 1.0, '{2,3,4}', true, NOW(), NOW()),

-- WHEEL (події) — common 1.5–1.8 | uncommon 1.1–1.3 | rare 0.4–0.6 | legendary 0.1
('Удача початківця', 'Beginner''s Luck', 'Отримайте жетон життя. Іноді везіння важливіше за досвід.', 'Gain one life token. Sometimes luck beats experience.', 'wheel', 'event', 1.8, '{1,2}', true, NOW(), NOW()),
('Сервер впав', 'Server Down', 'Ваш хмарний провайдер недоступний 10 хвилин гри. Презентуйте офлайн-рішення.', 'Your cloud provider is down for 10 game minutes. Present an offline solution.', 'wheel', 'event', 1.2, '{2,3,4,5}', true, NOW(), NOW()),
('Раптова перевірка', 'Surprise Audit', 'Ведучий ставить три технічних питання прямо зараз. Відповідає найменш технічний член команди.', 'Host asks three technical questions right now. The least technical team member answers.', 'wheel', 'event', 0.6, '{2,3,4,5}', true, NOW(), NOW()),
('Медіа-увага', 'Media Spotlight', 'TechCrunch хоче інтерв''ю прямо зараз. Опишіть продукт за 60 секунд.', 'TechCrunch wants an interview right now. Describe your product in 60 seconds.', 'wheel', 'event', 1.6, '{3,4,5}', true, NOW(), NOW()),
('Зміна погоди', 'Weather Change', 'Нічого не відбувається. Але команда хвилюється — втратіть 2 хвилини на паніку.', 'Nothing happens. But your team is anxious — lose 2 minutes to panic.', 'wheel', 'event', 0.1, '{1,2,3,4,5}', true, NOW(), NOW()),
('Несподіваний ментор', 'Surprise Mentor', 'Оберіть команду-суперника. Вони дають вам одну пораду — ви зобов''язані її використати.', 'Choose a rival team. They give you one piece of advice — you must use it.', 'wheel', 'event', 1.1, '{2,3,4}', true, NOW(), NOW()),
('Виграш гранту', 'Grant Win', 'Ви виграли мікрогрант $500. Як витратите? Поясніть за 1 хвилину.', 'You won a $500 microgrant. How will you spend it? Explain in 1 minute.', 'wheel', 'event', 1.5, '{1,2,3}', true, NOW(), NOW()),
('Відключення світла', 'Power Outage', 'Немає електрики 5 хвилин гри. Продовжуйте роботу без комп''ютерів.', 'No electricity for 5 game minutes. Continue working without computers.', 'wheel', 'event', 0.5, '{2,3,4}', true, NOW(), NOW()),
('Вірусний пост', 'Viral Post', 'Хтось написав про ваш продукт у X (Twitter). Хороше чи погане — невідомо. Підготуйтесь до обох варіантів.', 'Someone posted about your product on X. Good or bad — unknown. Prepare for both.', 'wheel', 'event', 1.3, '{3,4,5}', true, NOW(), NOW()),
('Квантова невизначеність', 'Quantum Uncertainty', 'Одна механіка вашого продукту тепер працює навпаки. Оберіть яка і адаптуйтесь.', 'One feature of your product now works in reverse. Choose which one and adapt.', 'wheel', 'event', 0.4, '{2,3,4,5}', true, NOW(), NOW()),

-- BOLT (прискорювачі) — common 2.0–2.5 | uncommon 1.6–1.8 | rare 0.9–1.2
('Турбо-мод', 'Turbo Mode', 'Ваша команда отримує додаткові 5 хвилин до кінця поточного раунду.', 'Your team gets an extra 5 minutes added to the current round.', 'bolt', 'accelerator', 2.0, '{1,2,3,4,5}', true, NOW(), NOW()),
('Безкоштовний API', 'Free API', 'Ви отримуєте необмежений безкоштовний доступ до будь-якого API на вибір. Використайте це.', 'You get unlimited free access to any API of your choice. Use it wisely.', 'bolt', 'accelerator', 1.8, '{1,2,3}', true, NOW(), NOW()),
('Зірковий найм', 'Star Hire', 'До вашої команди приєднується уявний senior-розробник. Що ви доручаєте йому першим?', 'An imaginary senior developer joins your team. What do you assign first?', 'bolt', 'accelerator', 1.0, '{2,3,4}', true, NOW(), NOW()),
('Венчурний дзвінок', 'VC Call', 'Інвестор готовий вкласти. У вас є 2 хвилини на pitch. Почали.', 'An investor is ready to invest. You have 2 minutes for a pitch. Go.', 'bolt', 'accelerator', 1.7, '{3,4,5}', true, NOW(), NOW()),
('Копіюй найкращих', 'Best Practice Steal', 'Оберіть будь-яку функцію з існуючого продукту і легально "надихніться" нею.', 'Choose any feature from an existing product and legally "get inspired" by it.', 'bolt', 'accelerator', 1.2, '{1,2,3,4}', true, NOW(), NOW()),
('Хакатон-буст', 'Hackathon Boost', 'Команда входить у стан потоку. Наступні 10 хвилин без жодних карток-перешкод.', 'The team enters flow state. Next 10 minutes without any obstacle cards.', 'bolt', 'accelerator', 2.5, '{2,3,4,5}', true, NOW(), NOW()),
('Готовий прототип', 'Ready Prototype', 'Пропустіть один етап розробки — вважайте його виконаним. Оберіть який.', 'Skip one development stage — consider it done. Choose which one.', 'bolt', 'accelerator', 1.6, '{3,4,5}', true, NOW(), NOW()),
('Медіа-партнер', 'Media Partner', 'Відомий блогер готовий безкоштовно прорекламувати вас. Підготуйте меседж за 90 секунд.', 'A popular blogger will promote you for free. Prepare your message in 90 seconds.', 'bolt', 'accelerator', 0.9, '{4,5}', true, NOW(), NOW()),
('Відкритий код', 'Open Source Win', 'Знайшли готову open-source бібліотеку яка вирішує вашу головну проблему. Назвіть яку.', 'Found an open-source library that solves your main problem. Name it.', 'bolt', 'accelerator', 1.7, '{1,2,3}', true, NOW(), NOW()),
('Подвійний XP', 'Double XP', 'Наступне нарахування балів для вашої команди множиться на 2. Зберіть цю картку.', 'The next score award for your team is multiplied by 2. Keep this card.', 'bolt', 'accelerator', 2.0, '{1,2,3,4,5}', true, NOW(), NOW()),

-- EYE (таємні місії) — uncommon 0.5–0.6 | rare 0.4 | legendary 0.1
('Подвійний агент', 'Double Agent', 'Таємно: дізнайтесь головну ідею сусідньої команди і використайте елемент у своєму продукті.', 'Secret: find out the main idea of the neighboring team and use an element in your product.', 'eye', 'secret', 0.4, '{2,3,4}', true, NOW(), NOW()),
('Тихий лідер', 'Silent Leader', 'Таємно: лідер команди мовчить, але керує жестами. Команда має зрозуміти без слів.', 'Secret: team leader stays silent but leads with gestures. Team must understand without words.', 'eye', 'secret', 0.4, '{1,2,3}', true, NOW(), NOW()),
('Інсайдерська інформація', 'Inside Intel', 'Таємно: ведучий шепоче вам одну реальну больову точку ринку. Використайте це.', 'Secret: host whispers one real market pain point to you. Use it.', 'eye', 'secret', 0.6, '{2,3,4,5}', true, NOW(), NOW()),
('Троянський кінь', 'Trojan Horse', 'Таємно: запропонуйте іншій команді "допомогу" яка насправді уповільнить їх на 3 хвилини.', 'Secret: offer another team "help" that will actually slow them down by 3 minutes.', 'eye', 'secret', 0.1, '{3,4,5}', true, NOW(), NOW()),
('Невидимий дедлайн', 'Hidden Deadline', 'Таємно: ведучий знає секретний час здачі вашого етапу. Він раніше ніж ви думаєте.', 'Secret: the host knows a secret submission time for your stage. It''s earlier than you think.', 'eye', 'secret', 0.1, '{2,3,4}', true, NOW(), NOW()),
('Шпигун у таборі', 'Camp Spy', 'Таємно: один член вашої команди 5 хвилин "працює" в іншій команді і звітує вам.', 'Secret: one team member "works" in another team for 5 minutes and reports back to you.', 'eye', 'secret', 0.4, '{3,4}', true, NOW(), NOW()),
('Секретна зброя', 'Secret Weapon', 'Таємно: ви можете один раз скасувати будь-яку картку суперника в цьому раунді.', 'Secret: you can cancel any opponent card once this round.', 'eye', 'secret', 0.1, '{1,2,3,4,5}', true, NOW(), NOW()),
('Невидима рука', 'Hidden Hand', 'Таємно: додайте до свого продукту функцію яку не озвучуєте до фінальної презентації.', 'Secret: add a feature to your product that you don''t reveal until the final presentation.', 'eye', 'secret', 0.6, '{2,3,4,5}', true, NOW(), NOW()),
('Ніч перед дедлайном', 'Pre-deadline Night', 'Таємно: ваша команда "не спала всю ніч" — один учасник може тричі попросити repeat питання.', 'Secret: your team "pulled an all-nighter" — one member can ask to repeat a question three times.', 'eye', 'secret', 0.4, '{4,5}', true, NOW(), NOW()),
('Зворотній зв''язок від майбутнього', 'Feedback from Future', 'Таємно: ведучий каже вам один критичний відгук від "майбутнього користувача". Адаптуйтесь.', 'Secret: host tells you one critical review from a "future user". Adapt accordingly.', 'eye', 'secret', 0.6, '{3,4,5}', true, NOW(), NOW()),

-- MASK (обмін) — uncommon 0.5 | rare 0.4 | legendary 0.1
('Обмін талантами', 'Talent Swap', 'Обміняйтесь одним учасником з іншою командою на 7 хвилин. Домовтесь хто.', 'Swap one team member with another team for 7 minutes. Decide who.', 'mask', 'trade', 0.5, '{2,3,4}', true, NOW(), NOW()),
('Продай ідею', 'Idea Sale', 'Запропонуйте одну вашу ідею іншій команді в обмін на їхній жетон życia.', 'Offer one of your ideas to another team in exchange for their life token.', 'mask', 'trade', 0.4, '{3,4,5}', true, NOW(), NOW()),
('Картковий аукціон', 'Card Auction', 'Продайте цю картку іншій команді за домовленою "ціною". Ціна — публічне визнання їх ідеї.', 'Sell this card to another team at a negotiated "price". Price = public acknowledgment of their idea.', 'mask', 'trade', 0.4, '{2,3,4,5}', true, NOW(), NOW()),
('Стратегічний альянс', 'Strategic Alliance', 'Об''єднайте зусилля з однією командою на 5 хвилин. Результат належить обом.', 'Join forces with one team for 5 minutes. The result belongs to both.', 'mask', 'trade', 0.5, '{3,4,5}', true, NOW(), NOW()),
('Викрадення технології', 'Tech Steal', 'Оберіть одну технологію з презентації іншої команди і офіційно "ліцензуйте" її.', 'Choose one technology from another team''s presentation and officially "license" it.', 'mask', 'trade', 0.1, '{3,4}', true, NOW(), NOW()),
('Злиття та поглинання', 'Merger & Acquisition', 'Запропонуйте злиття з іншою командою. Якщо вони погоджуються — об''єднані бали діляться 60/40.', 'Propose a merger with another team. If agreed — combined scores split 60/40.', 'mask', 'trade', 0.4, '{4,5}', true, NOW(), NOW()),
('Чорний ринок ідей', 'Idea Black Market', 'Таємно запропонуйте іншій команді вашу проблему в обмін на їхнє рішення.', 'Secretly offer another team your problem in exchange for their solution.', 'mask', 'trade', 0.4, '{2,3,4}', true, NOW(), NOW()),
('Крос-промо', 'Cross-Promo', 'Домовтесь з іншою командою про взаємну згадку в презентаціях. Обидві команди +1 бал.', 'Agree with another team on mutual mention in presentations. Both teams +1 point.', 'mask', 'trade', 0.5, '{4,5}', true, NOW(), NOW()),
('Патентна суперечка', 'Patent Dispute', 'Звинуватіть іншу команду у використанні вашої ідеї. Журі вирішує за 2 хвилини.', 'Accuse another team of using your idea. Jury decides in 2 minutes.', 'mask', 'trade', 0.4, '{3,4,5}', true, NOW(), NOW()),
('Піратська копія', 'Pirate Copy', 'Візьміть будь-яку скинуту картку з купи відбою і застосуйте її зараз.', 'Take any discarded card from the discard pile and apply it now.', 'mask', 'trade', 0.5, '{2,3,4,5}', true, NOW(), NOW()),

-- SPIRAL (plot twist) — всі legendary, вага 0.1, тільки раунд 5
('Великий розворот', 'The Big Pivot', 'Повністю змініть цільову аудиторію вашого продукту. У вас є 3 хвилини на нову презентацію.', 'Completely change your target audience. You have 3 minutes for a new presentation.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Конкуренти об''єдналися', 'Rivals United', 'Всі інші команди утворили альянс проти вас. Як вижити на ринку?', 'All other teams formed an alliance against you. How do you survive in the market?', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Регулятор заблокував', 'Regulator Blocked', 'Ваш продукт заблокований регулятором. Переосмисліть за 5 хвилин або програєте раунд.', 'Your product is blocked by regulators. Rethink in 5 minutes or lose the round.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Засновник пішов', 'Founder Left', 'CEO покинув компанію. Хто тепер лідер і яка нова візія? Вирішіть за 2 хвилини.', 'The CEO left the company. Who is the new leader and what is the new vision? Decide in 2 minutes.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Вірусний скандал', 'Viral Scandal', 'Ваш продукт потрапив у центр медіа-скандалу. Підготуйте антикризову заяву за 3 хвилини.', 'Your product is at the center of a media scandal. Prepare a crisis statement in 3 minutes.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Технологія застаріла', 'Tech Obsolete', 'Ключова технологія вашого продукту щойно стала застарілою. Що замість неї?', 'The key technology of your product just became obsolete. What replaces it?', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Ринок зник', 'Market Gone', 'Ваша ніша зникла через новий закон. Знайдіть суміжний ринок за 4 хвилини.', 'Your niche disappeared due to a new law. Find an adjacent market in 4 minutes.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Інвестор забрав гроші', 'Investor Pulled Out', 'Головний інвестор вийшов з проєкту. Презентуйте bootstrap-стратегію виживання.', 'Main investor pulled out. Present a bootstrap survival strategy.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Злиття з ворогом', 'Enemy Merger', 'Вас поглинув найбільший конкурент. Як зберегти команду і продукт всередині корпорації?', 'You were acquired by your biggest competitor. How do you preserve the team and product inside a corporation?', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),
('Фінальна перевірка', 'Final Audit', 'Весь ваш прогрес переглядається з нуля. Захистіть кожне рішення за останні 5 раундів.', 'All your progress is reviewed from scratch. Defend every decision from the last 5 rounds.', 'spiral', 'plot_twist', 0.1, '{5}', true, NOW(), NOW()),

-- ALERT (ML-кризи) — common 1.5 | uncommon 0.9–1.1 | rare 0.5
('Overfitting Alert', 'Overfitting Alert', 'Ваша модель ідеально працює на тренувальних даних і провалюється на реальних. Що робите?', 'Your model works perfectly on training data and fails on real data. What do you do?', 'alert', 'ml_crisis', 1.5, '{2,3,4,5}', true, NOW(), NOW()),
('Упереджені дані', 'Biased Dataset', 'Виявлено: ваш датасет містить системне упередження. Продукт дискримінує. Вирішіть за 3 хв.', 'Discovered: your dataset has systematic bias. The product discriminates. Fix in 3 minutes.', 'alert', 'ml_crisis', 1.1, '{2,3,4,5}', true, NOW(), NOW()),
('Чорна скринька', 'Black Box Problem', 'Регулятор вимагає пояснити кожне рішення вашого AI. Explainability або штраф.', 'Regulator demands explanation for every AI decision. Explainability or fine.', 'alert', 'ml_crisis', 1.0, '{3,4,5}', true, NOW(), NOW()),
('Витік даних', 'Data Breach', 'Персональні дані 10,000 користувачів скомпрометовані. У вас є 5 хвилин на план дій.', 'Personal data of 10,000 users is compromised. You have 5 minutes for an action plan.', 'alert', 'ml_crisis', 0.5, '{3,4,5}', true, NOW(), NOW()),
('Модель галюцинує', 'Hallucination Mode', 'Ваш LLM впевнено видає неправильні відповіді. Як ви це виявили і що робите далі?', 'Your LLM confidently gives wrong answers. How did you discover it and what do you do next?', 'alert', 'ml_crisis', 1.5, '{2,3,4,5}', true, NOW(), NOW()),
('Дрейф моделі', 'Model Drift', 'Через 3 місяці після запуску точність впала на 40%. Автоматичного перенавчання немає.', 'Three months after launch, accuracy dropped 40%. No automatic retraining in place.', 'alert', 'ml_crisis', 0.9, '{3,4,5}', true, NOW(), NOW()),
('Отруєння даних', 'Data Poisoning', 'Хтось навмисно вніс неправильні дані у вашу тренувальну вибірку. Як виявити і виправити?', 'Someone deliberately injected bad data into your training set. How to detect and fix?', 'alert', 'ml_crisis', 0.5, '{3,4,5}', true, NOW(), NOW()),
('GPU закінчились', 'GPU Shortage', 'Compute-ресурси вичерпано. Треба переробити рішення для CPU або edge-пристроїв.', 'Compute resources exhausted. Need to rework solution for CPU or edge devices.', 'alert', 'ml_crisis', 1.0, '{2,3,4}', true, NOW(), NOW()),
('Конфіденційність vs точність', 'Privacy vs Accuracy', 'Єдиний спосіб підвищити точність — зібрати більше персональних даних. GDPR проти вас.', 'The only way to improve accuracy is to collect more personal data. GDPR is against you.', 'alert', 'ml_crisis', 1.1, '{3,4,5}', true, NOW(), NOW()),
('Adversarial Attack', 'Adversarial Attack', 'Хакер знайшов спосіб обманути вашу модель одним пікселем. Що це означає для безпеки?', 'A hacker found a way to fool your model with one pixel. What does this mean for security?', 'alert', 'ml_crisis', 0.9, '{3,4,5}', true, NOW(), NOW());
